### ISSUE TITLE
Document/Folder Titles Unnecessarily Short

### ISSUE THREAD

**Issue by peteritism** [wtg/flagship_docs_4#45]
Document and Folder Titles greater than 15 characters are cut down to 13 characters plus an ellipsis in both list and grid view. In many cases, it's difficult to understand what the file is because the name is so short. Within list view, it could easily be two or three times as long, and within grid view the same is true; however, it should be wrapped to a second or third line.

**Comment by gbprz** [comment]
Thanks for the heads up, I'm currently working on changing up the UI a little bit (not my strong suit), but I'm definitely taking this into account as I work on it. I apologize for the negative experience.

**Comment by gbprz** [comment]
The new branch I'm working on can be found here: https://github.com/wtg/flagship_docs_4/tree/polymerUI
